Server:
  RunMode: debug
  HttpPort: 8001
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: laravel
  TablePrefix: lv_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: cyz
  Issuer: ginpro-service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: chengyaozong@126.com
  Password: cyz881541
  IsSSL: true
  From: chengyaozong@126.com
  To:
    - chengyaozong@qq.com
Redis:
  Host: 127.0.0.1:6379
  Password:
  MaxIdle: 30
  MaxActive: 30
  IdleTimeout: 200
MongoDB:
  #link: mongodb://user:password@localhost:27017/?authSource=admin
  Host: mongodb://10.98.15.24:27017
  MaxPoolSize: 30
  Timeout: 10
RabbitMq:
  Host: amqp://guest:guest@localhost:5672/
Es:
  Host: http://10.98.15.24:9200/,http://10.98.15.24:9200/